name: Process Markdown with Questions

on:
  push:
    branches:
      - main  # or any branch you want this action to run on
    paths:
      - 'lectures/assets/questions.json'  # trigger action on changes to this specific file

jobs:
  process-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script
        run: python lectures/assets/questions.py

      - name: Commit and push changes
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update markdown with new forms."
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}